### PR TITLE
Subscriptions coalescer can now track more than a single subscription, eliminating bug where subscriptions would not unsubscribe

### LINKED ISSUE #603: Aborted subscription still receives messages (`slotUnsubscribe` not called)
## Overview

When trying to integrate a new RPC node provider, we've noticed that the WebSocket connection is getting overwhelmed with unnecessary subscription events. It seems that RPC subscriptions are not terminating properly in situations with multiple ongoing subscriptions. 

## Steps to reproduce

1. Open the sandbox example here: https://codesandbox.io/p/sandbox/solana-javascript-sdk-technology-preview-3-forked-fsmc5n
2. Open your browser's Dev tools –> Network tab -> Socket filter and watch the WebSocket messages
3. Click on "Subscribe accounts"
4. Click on "Subscribe slots"
5. Click on "Unsubscribe slots"
6. Observe that the slot logs in the UI stop, but WebSocket messages from the server continue to arrive

## Description of bug

Even after aborting a given subscription (e.g. `slotSubscribe`), the WebSocket connection continues to receive messages related to that subscription. We would expect the corresponding `slotUnsubscribe` method to be called.

In some other cases it does seem to work correctly - for example, when clicking "Subscribe slots" first, and then "Subscribe accounts".

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

This data structure only ever tracked one subscription at a time. Untracked subscriptions could become stuck and never send their unsubscribe message, even after the last consumer aborted the subscription.

#### Summary of Changes

Write it like you mean it.

#### Test Plan

```ts
import { address, createSolanaRpcSubscriptions } from './index';

const rpcSubscriptions = createSolanaRpcSubscriptions('wss://api.devnet.solana.com');

void (async () => {
    const accountNotifications = await rpcSubscriptions
        .accountNotifications(address('Ftk9ELv51cE7zZ8swsCLtcx8Vt8rt7dZC8gKMRSfKEgV'))
        .subscribe({ abortSignal: AbortSignal.timeout(10000) });
    const slotNotifications = await rpcSubscriptions
        .slotNotifications()
        .subscribe({ abortSignal: AbortSignal.timeout(1000) });

    void (async () => {
        for await (const notif of accountNotifications) {
            console.log('Account notification', notif);
        }
        console.log('Done accounts');
    })();
    void (async () => {
        for await (const notif of slotNotifications) {
            console.log('Slot notification', notif);
        }
        console.log('Done slots');
    })();
})();
```

Observe that the unsubscribe message is sent when the slot subscription is aborted.

Fixes #603.

### CODE REVIEW

**Comment by steveluscher** [comment]
* **#618** <a href="https://app.graphite.dev/github/pr/anza-xyz/kit/618?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/anza-xyz/kit/618?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-pubsub-plan-test.ts [hunk 1]
```diff
@@ -304,5 +304,36 @@ describe('executeRpcPubSubSubscriptionPlan', () => {
...
+                    unsubscribeMethodName: 'thingUnsubscribe',
+                }).catch(() => {});
+                await jest.runAllTimersAsync();
+                receiveMessage({ id: lastMessageId, jsonrpc: '2.0', result: (expectedSubscriptionId = 456) });
+            });
+            it('sends the unsubscribe message when the prior subscription aborts', () => {
+                mockSend.mockClear();
+                abortController.abort();
+                expect(mockSend).toHaveBeenCalledWith(
+                    expect.objectContaining({ method: 'thingUnsubscribe', params: [priorSubscriptionId] }),
```
Comment (steveluscher) [inline packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-pubsub-plan-test.ts:327]: This acts as a regression test for #603; tests that the tracker can track two subscriptions independently.

File: packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts [hunk 2]
```diff
@@ -50,17 +57,17 @@ function augmentSubscriberCountAndReturnNewCount(
...
-    if (!subscriberCountBySubscriptionId && amount > 0) {
-        subscriberCountBySubscriptionIdByChannel.set(
-            channel,
-            (subscriberCountBySubscriptionId = { [subscriptionId]: 0 }),
-        );
+    const subscriberCountBySubscriptionId = getSubscriberCountBySubscriptionIdForChannel(channel);
+    if (!subscriberCountBySubscriptionId[subscriptionId] && amount > 0) {
+        subscriberCountBySubscriptionId[subscriptionId] = 0;
     }
-    if (subscriberCountBySubscriptionId?.[subscriptionId] !== undefined) {
```
Comment (steveluscher) [inline packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts:60]: LOL.

This line meant that if you were tracking at least one subscription, it would never bother to track new ones.

**Review by lorisleiva — APPROVED** [review]
Interesting! Thanks for the fix. 🙏
