### PR TITLE
s/readableIndexes/readonlyIndexes/ in `AddressLookupTable` type

### LINKED ISSUE #412: rpc-api: AddressLookupTable readableIndexes should be readonlyIndexes
## Steps to reproduce

Using the @solana/kit RPC client to `getTransaction` with any TX with address table lookups, the returned object has `readonlyIndexes`, not `readableIndexes`.

## Description of bug

https://github.com/anza-xyz/kit/blob/79d1030ae9ab9fd68e183e28380af089b88bcde6/packages/rpc-api/src/getTransaction.ts#L67

should be `readonlyIndexes`

https://solana.com/docs/rpc/json-structures#transactions:~:text=a%20lookup%20table.-,readonlyIndexes,-%3A%20%3Carray%5Bnumber%5D%3E

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

1. These were misspelled in the return type of `getTransaction()`
2. Because of the misspelling, the data structure from the `getTransaction()` API and the `CompiledTransactionMessage` type were incompatible.

#### Summary of Changes

1. The misspelling was corrected in the return type of the `getTransaction()` API
2. The alternate spellings in `CompiledTransactionMessage` were deprecated, and duplicated as the API's spellings. We can remove the `*Indices` spellings in a future major version.

Fixes #412.

### CODE REVIEW

**Comment by steveluscher** [comment]
* **#433** <a href="https://app.graphite.dev/github/pr/anza-xyz/kit/433?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/anza-xyz/kit/433?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/transaction-messages/src/codecs/address-table-lookup.ts [hunk 1]
```diff
@@ -35,13 +33,27 @@ export function getAddressTableLookupEncoder(): VariableSizeEncoder<AddressTable
...
+            ]),
+            lookupTable =>
+                'readableIndices' in lookupTable
+                    ? ({
+                          ...lookupTable,
+                          readonlyIndexes: lookupTable.readableIndices,
+                          // @ts-expect-error Remove when `readableIndices` and `writableIndices` are removed.
+                          writableIndexes: lookupTable.writableIndices,
+                      } as AddressTableLookup)
+                    : lookupTable,
```
Comment (steveluscher) [inline packages/transaction-messages/src/codecs/address-table-lookup.ts:52]: Gross.

**Review by mcintyre94 — APPROVED** [review]
